# Generated by Django 4.1.7 on 2023-03-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_actor_category_genre_movie_ratingstar_reviews_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='screenshots',
            field=models.ImageField(default=1, upload_to='movies/', verbose_name='Скриншоты'),
            preserve_default=False,
        ),
    ]
