# Generated by Django 4.1.7 on 2023-03-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_screenshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video',
            field=models.FileField(default=1, upload_to='movies/', verbose_name='Трейлер'),
            preserve_default=False,
        ),
    ]
