# Generated by Django 4.1.7 on 2023-03-20 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='video',
        ),
    ]
