# Generated by Django 4.1.7 on 2023-03-20 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='star',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies.ratingstar', verbose_name='Звезда'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie', verbose_name='Фильм'),
        ),
    ]
